### ISSUE TITLE
AssertionError domain.name not in self.domains

### ISSUE THREAD

**Issue by nicolas-robin** [m-labs/nmigen#307]
Since a7be3b4, this code fails :

Code :
```python
from nmigen import *
from nmigen_boards.ice40_hx8k_b_evn import ICE40HX8KBEVNPlatform

platform = ICE40HX8KBEVNPlatform()
top = Module()
top.d.sync += platform.request("led").o.eq(1)
platform.build(top)
```

Error :
```python
Traceback (most recent call last):
  File "[...]/sandbox.py", line 7, in <module>
    platform.build(top)
  File "[...]/venv/lib/python3.7/site-packages/nmigen/build/plat.py", line 77, in build
    plan = self.prepare(elaboratable, name, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/nmigen/build/plat.py", line 147, in prepare
    fragment = fragment.prepare(ports=self.iter_ports(), missing_domain=lambda name: None)
  File "[...]/venv/lib/python3.7/site-packages/nmigen/hdl/ir.py", line 556, in prepare
    new_domains = fragment._propagate_domains(missing_domain)
  File "[...]/venv/lib/python3.7/site-packages/nmigen/hdl/ir.py", line 403, in _propagate_domains
    self._propagate_domains_up()
  File "[...]/venv/lib/python3.7/site-packages/nmigen/hdl/ir.py", line 359, in _propagate_domains_up
    self.add_domains(domain)
  File "[...]/venv/lib/python3.7/site-packages/nmigen/hdl/ir.py", line 145, in add_domains
    assert domain.name not in self.domains
AssertionError
```

**Comment by smunaut** [comment]
Same error happens when trying to run glasgow with latest nMigen.
(seen by me, @esden @miek at least)

**Comment by smunaut** [comment]
Not sure if this is the correct fix, but this seems to work for me :

```diff
diff --git a/nmigen/hdl/ir.py b/nmigen/hdl/ir.py
index 26dec85..2b8b74c 100644
--- a/nmigen/hdl/ir.py
+++ b/nmigen/hdl/ir.py
@@ -142,7 +142,7 @@ class Fragment:
     def add_domains(self, *domains):
         for domain in flatten(domains):
             assert isinstance(domain, ClockDomain)
-            assert domain.name not in self.domains
+            assert (domain.name not in self.domains) or (self.domains[domain.name] == domain)
             self.domains[domain.name] = domain
 
     def iter_domains(self):

```

**Comment by whitequark** [comment]
Likely not the correct fix, but an acceptable workaround.

**Comment by whitequark** [comment]
Fixed [upstream](https://github.com/nmigen/nmigen).
